library(dplyr)
library(readxl)
library(ggplot2)
library(sqldf)
library(stringr)
library(writexl)


Seoul_traffic <- read_excel('c:/Big Data Contest/Seoul_traffic_final.xlsx')

Seoul_traffic <- Seoul_traffic %>% mutate(Code = row_number()) %>% filter(52139 <= Code )

Seoul_traffic <- Seoul_traffic %>% mutate(Time0_2 = print(Seoul_traffic$Time_0 + Seoul_traffic$Time_1 + Seoul_traffic$Time_2)) %>% 
  mutate(Time3_5 = print(Seoul_traffic$Time_3 + Seoul_traffic$Time_4 + Seoul_traffic$Time_5)) %>% 
  mutate(Time6_8 = print(Seoul_traffic$Time_6 + Seoul_traffic$Time_7 + Seoul_traffic$Time_8)) %>% 
  mutate(Time9_11 = print(Seoul_traffic$Time_9 + Seoul_traffic$Time_10 + Seoul_traffic$Time_11)) %>% 
  mutate(Time12_14 = print(Seoul_traffic$Time_12 + Seoul_traffic$Time_13 + Seoul_traffic$Time_14)) %>% 
  mutate(Time15_17 = print(Seoul_traffic$Time_15 + Seoul_traffic$Time_16 + Seoul_traffic$Time_17)) %>% 
  mutate(Time18_20 = print(Seoul_traffic$Time_18 + Seoul_traffic$Time_19 + Seoul_traffic$Time_20)) %>% 
  mutate(Time21_23 = print(Seoul_traffic$Time_21 + Seoul_traffic$Time_22 + Seoul_traffic$Time_23))

Seoul_traffic <- Seoul_traffic %>% select(-Time_0, -Time_1, -Time_2, -Time_3, -Time_4, -Time_5, -Time_6, -Time_7, -Time_8, -Time_9, -Time_10, -Time_11, -Time_12, -Time_13, -Time_14, -Time_15, -Time_16, -Time_17, -Time_18, -Time_19, -Time_20, -Time_21, -Time_22, -Time_23)

#결측값 변환하고 합치기 위해 썼던 코딩내역
#Seoul_traffic1 <- Seoul_traffic %>% select(-Direction)
#Seoul_traffic1[is.na(Seoul_traffic1)] <- 0
#Seoul_traffic <- Seoul_traffic %>% select(Code, Direction)
#Seoul_traffic1 <- Seoul_traffic1 %>% inner_join(Seoul_traffic, by=c('Code' = 'Code'))

Seoul_traffic %>% distinct(Point_No) %>% View()

P_N_A_1 <- Seoul_traffic %>% filter(Point_No == 'A-01')
P_N_A_2 <- Seoul_traffic %>% filter(Point_No == 'A-02')
P_N_A_3 <- Seoul_traffic %>% filter(Point_No == 'A-03')
P_N_A_4 <- Seoul_traffic %>% filter(Point_No == 'A-04')
P_N_A_5 <- Seoul_traffic %>% filter(Point_No == 'A-05')
P_N_A_6 <- Seoul_traffic %>% filter(Point_No == 'A-06')
P_N_A_7 <- Seoul_traffic %>% filter(Point_No == 'A-07')
P_N_A_8 <- Seoul_traffic %>% filter(Point_No == 'A-08')
P_N_A_9 <- Seoul_traffic %>% filter(Point_No == 'A-09')
P_N_A_10 <- Seoul_traffic %>% filter(Point_No == 'A-10')
P_N_A_11 <- Seoul_traffic %>% filter(Point_No == 'A-11')
P_N_A_12 <- Seoul_traffic %>% filter(Point_No == 'A-12')
P_N_A_13 <- Seoul_traffic %>% filter(Point_No == 'A-13')
P_N_A_14 <- Seoul_traffic %>% filter(Point_No == 'A-14')
P_N_A_15 <- Seoul_traffic %>% filter(Point_No == 'A-15')
P_N_A_16 <- Seoul_traffic %>% filter(Point_No == 'A-16')
P_N_A_17 <- Seoul_traffic %>% filter(Point_No == 'A-17')
P_N_A_18 <- Seoul_traffic %>% filter(Point_No == 'A-18')
P_N_A_19 <- Seoul_traffic %>% filter(Point_No == 'A-19')
P_N_A_20 <- Seoul_traffic %>% filter(Point_No == 'A-20')
P_N_A_21 <- Seoul_traffic %>% filter(Point_No == 'A-21')
P_N_A_22 <- Seoul_traffic %>% filter(Point_No == 'A-22')
P_N_A_23 <- Seoul_traffic %>% filter(Point_No == 'A-23')
P_N_A_24 <- Seoul_traffic %>% filter(Point_No == 'A-24')

P_N_B_1 <- Seoul_traffic %>% filter(Point_No == 'B-01')
P_N_B_2 <- Seoul_traffic %>% filter(Point_No == 'B-02')
P_N_B_3 <- Seoul_traffic %>% filter(Point_No == 'B-03')
P_N_B_4 <- Seoul_traffic %>% filter(Point_No == 'B-04')
P_N_B_5 <- Seoul_traffic %>% filter(Point_No == 'B-05')
P_N_B_6 <- Seoul_traffic %>% filter(Point_No == 'B-06')
P_N_B_7 <- Seoul_traffic %>% filter(Point_No == 'B-07')
P_N_B_8 <- Seoul_traffic %>% filter(Point_No == 'B-08')
P_N_B_9 <- Seoul_traffic %>% filter(Point_No == 'B-09')
P_N_B_10 <- Seoul_traffic %>% filter(Point_No == 'B-10')
P_N_B_11 <- Seoul_traffic %>% filter(Point_No == 'B-11')
P_N_B_12 <- Seoul_traffic %>% filter(Point_No == 'B-12')
P_N_B_13 <- Seoul_traffic %>% filter(Point_No == 'B-13')
P_N_B_14 <- Seoul_traffic %>% filter(Point_No == 'B-14')
P_N_B_15 <- Seoul_traffic %>% filter(Point_No == 'B-15')
P_N_B_16 <- Seoul_traffic %>% filter(Point_No == 'B-16')
P_N_B_17 <- Seoul_traffic %>% filter(Point_No == 'B-17')
P_N_B_18 <- Seoul_traffic %>% filter(Point_No == 'B-18')
P_N_B_19 <- Seoul_traffic %>% filter(Point_No == 'B-19')
P_N_B_20 <- Seoul_traffic %>% filter(Point_No == 'B-20')
P_N_B_21 <- Seoul_traffic %>% filter(Point_No == 'B-21')
P_N_B_22 <- Seoul_traffic %>% filter(Point_No == 'B-22')
P_N_B_23 <- Seoul_traffic %>% filter(Point_No == 'B-23')
P_N_B_24 <- Seoul_traffic %>% filter(Point_No == 'B-24')
P_N_B_25 <- Seoul_traffic %>% filter(Point_No == 'B-25')
P_N_B_26 <- Seoul_traffic %>% filter(Point_No == 'B-26')
P_N_B_27 <- Seoul_traffic %>% filter(Point_No == 'B-27')
P_N_B_28 <- Seoul_traffic %>% filter(Point_No == 'B-28')
P_N_B_29 <- Seoul_traffic %>% filter(Point_No == 'B-29')
P_N_B_30 <- Seoul_traffic %>% filter(Point_No == 'B-30')
P_N_B_31 <- Seoul_traffic %>% filter(Point_No == 'B-31')
P_N_B_32 <- Seoul_traffic %>% filter(Point_No == 'B-32')
P_N_B_33 <- Seoul_traffic %>% filter(Point_No == 'B-33')
P_N_B_34 <- Seoul_traffic %>% filter(Point_No == 'B-34')
P_N_B_35 <- Seoul_traffic %>% filter(Point_No == 'B-35')
P_N_B_36 <- Seoul_traffic %>% filter(Point_No == 'B-36')
P_N_B_37 <- Seoul_traffic %>% filter(Point_No == 'B-37')

P_N_C_1 <- Seoul_traffic %>% filter(Point_No == 'C-01')
P_N_C_2 <- Seoul_traffic %>% filter(Point_No == 'C-02')
P_N_C_3 <- Seoul_traffic %>% filter(Point_No == 'C-03')
P_N_C_4 <- Seoul_traffic %>% filter(Point_No == 'C-04')
P_N_C_5 <- Seoul_traffic %>% filter(Point_No == 'C-05')
P_N_C_6 <- Seoul_traffic %>% filter(Point_No == 'C-06')
P_N_C_7 <- Seoul_traffic %>% filter(Point_No == 'C-07')
P_N_C_8 <- Seoul_traffic %>% filter(Point_No == 'C-08')
P_N_C_9 <- Seoul_traffic %>% filter(Point_No == 'C-09')
P_N_C_10 <- Seoul_traffic %>% filter(Point_No == 'C-10')
P_N_C_11 <- Seoul_traffic %>% filter(Point_No == 'C-11')
P_N_C_12 <- Seoul_traffic %>% filter(Point_No == 'C-12')
P_N_C_13 <- Seoul_traffic %>% filter(Point_No == 'C-13')
P_N_C_14 <- Seoul_traffic %>% filter(Point_No == 'C-14')
P_N_C_15 <- Seoul_traffic %>% filter(Point_No == 'C-15')
P_N_C_16 <- Seoul_traffic %>% filter(Point_No == 'C-16')
P_N_C_17 <- Seoul_traffic %>% filter(Point_No == 'C-17')
P_N_C_18 <- Seoul_traffic %>% filter(Point_No == 'C-18')
P_N_C_19 <- Seoul_traffic %>% filter(Point_No == 'C-19')
P_N_C_20 <- Seoul_traffic %>% filter(Point_No == 'C-20')
P_N_C_21 <- Seoul_traffic %>% filter(Point_No == 'C-21')
P_N_C_22 <- Seoul_traffic %>% filter(Point_No == 'C-22')

P_N_D_1 <- Seoul_traffic %>% filter(Point_No == 'D-01')
P_N_D_2 <- Seoul_traffic %>% filter(Point_No == 'D-02')
P_N_D_3 <- Seoul_traffic %>% filter(Point_No == 'D-03')
P_N_D_4 <- Seoul_traffic %>% filter(Point_No == 'D-04')
P_N_D_5 <- Seoul_traffic %>% filter(Point_No == 'D-05')
P_N_D_6 <- Seoul_traffic %>% filter(Point_No == 'D-06')
P_N_D_7 <- Seoul_traffic %>% filter(Point_No == 'D-07')
P_N_D_8 <- Seoul_traffic %>% filter(Point_No == 'D-08')
P_N_D_9 <- Seoul_traffic %>% filter(Point_No == 'D-09')
P_N_D_10 <- Seoul_traffic %>% filter(Point_No == 'D-10')
P_N_D_11 <- Seoul_traffic %>% filter(Point_No == 'D-11')
P_N_D_12 <- Seoul_traffic %>% filter(Point_No == 'D-12')
P_N_D_13 <- Seoul_traffic %>% filter(Point_No == 'D-13')
P_N_D_14 <- Seoul_traffic %>% filter(Point_No == 'D-14')
P_N_D_15 <- Seoul_traffic %>% filter(Point_No == 'D-15')
P_N_D_16 <- Seoul_traffic %>% filter(Point_No == 'D-16')
P_N_D_17 <- Seoul_traffic %>% filter(Point_No == 'D-17')
P_N_D_18 <- Seoul_traffic %>% filter(Point_No == 'D-18')
P_N_D_19 <- Seoul_traffic %>% filter(Point_No == 'D-19')
P_N_D_20 <- Seoul_traffic %>% filter(Point_No == 'D-20')
P_N_D_21 <- Seoul_traffic %>% filter(Point_No == 'D-21')
P_N_D_22 <- Seoul_traffic %>% filter(Point_No == 'D-22')
P_N_D_23 <- Seoul_traffic %>% filter(Point_No == 'D-23')
P_N_D_24 <- Seoul_traffic %>% filter(Point_No == 'D-24')
P_N_D_25 <- Seoul_traffic %>% filter(Point_No == 'D-25')
P_N_D_26 <- Seoul_traffic %>% filter(Point_No == 'D-26')
P_N_D_27 <- Seoul_traffic %>% filter(Point_No == 'D-27')
P_N_D_28 <- Seoul_traffic %>% filter(Point_No == 'D-28')
P_N_D_29 <- Seoul_traffic %>% filter(Point_No == 'D-29')
P_N_D_30 <- Seoul_traffic %>% filter(Point_No == 'D-30')
P_N_D_31 <- Seoul_traffic %>% filter(Point_No == 'D-31')
P_N_D_32 <- Seoul_traffic %>% filter(Point_No == 'D-32')
P_N_D_33 <- Seoul_traffic %>% filter(Point_No == 'D-33')
P_N_D_34 <- Seoul_traffic %>% filter(Point_No == 'D-34')
P_N_D_35 <- Seoul_traffic %>% filter(Point_No == 'D-35')
P_N_D_36 <- Seoul_traffic %>% filter(Point_No == 'D-36')
P_N_D_37 <- Seoul_traffic %>% filter(Point_No == 'D-37')
P_N_D_38 <- Seoul_traffic %>% filter(Point_No == 'D-38')
P_N_D_39 <- Seoul_traffic %>% filter(Point_No == 'D-39')
P_N_D_40 <- Seoul_traffic %>% filter(Point_No == 'D-40')
P_N_D_41 <- Seoul_traffic %>% filter(Point_No == 'D-41')
P_N_D_42 <- Seoul_traffic %>% filter(Point_No == 'D-42')
P_N_D_43 <- Seoul_traffic %>% filter(Point_No == 'D-43')
P_N_D_44 <- Seoul_traffic %>% filter(Point_No == 'D-44')
P_N_D_45 <- Seoul_traffic %>% filter(Point_No == 'D-45')
P_N_D_46 <- Seoul_traffic %>% filter(Point_No == 'D-46')
P_N_D_47 <- Seoul_traffic %>% filter(Point_No == 'D-47')
P_N_D_48 <- Seoul_traffic %>% filter(Point_No == 'D-48')
## P_N_D_49 <- Seoul_traffic %>% filter(Point_No == 'D-49')
P_N_D_50 <- Seoul_traffic %>% filter(Point_No == 'D-50')
P_N_D_51 <- Seoul_traffic %>% filter(Point_No == 'D-51')
P_N_D_52 <- Seoul_traffic %>% filter(Point_No == 'D-52')
P_N_D_53 <- Seoul_traffic %>% filter(Point_No == 'D-53')
P_N_D_54 <- Seoul_traffic %>% filter(Point_No == 'D-54')

P_N_F_1 <- Seoul_traffic %>% filter(Point_No == 'F-01')
P_N_F_2 <- Seoul_traffic %>% filter(Point_No == 'F-02')
P_N_F_3 <- Seoul_traffic %>% filter(Point_No == 'F-03')
P_N_F_4 <- Seoul_traffic %>% filter(Point_No == 'F-04')
P_N_F_5 <- Seoul_traffic %>% filter(Point_No == 'F-05')
P_N_F_6 <- Seoul_traffic %>% filter(Point_No == 'F-06')
P_N_F_7 <- Seoul_traffic %>% filter(Point_No == 'F-07')
P_N_F_8 <- Seoul_traffic %>% filter(Point_No == 'F-08')
P_N_F_9 <- Seoul_traffic %>% filter(Point_No == 'F-09')


write.csv(P_N_A_1, 'c:/Big Data Contest/P_N_A_1.csv')
write.csv(P_N_A_2, 'c:/Big Data Contest/P_N_A_2.csv')
write.csv(P_N_A_3, 'c:/Big Data Contest/P_N_A_3.csv')
write.csv(P_N_A_4, 'c:/Big Data Contest/P_N_A_4.csv')
write.csv(P_N_A_5, 'c:/Big Data Contest/P_N_A_5.csv')
write.csv(P_N_A_6, 'c:/Big Data Contest/P_N_A_6.csv')
write.csv(P_N_A_7, 'c:/Big Data Contest/P_N_A_7.csv')
write.csv(P_N_A_8, 'c:/Big Data Contest/P_N_A_8.csv')
write.csv(P_N_A_9, 'c:/Big Data Contest/P_N_A_9.csv')
write.csv(P_N_A_10, 'c:/Big Data Contest/P_N_A_10.csv')
write.csv(P_N_A_11, 'c:/Big Data Contest/P_N_A_11.csv')
write.csv(P_N_A_12, 'c:/Big Data Contest/P_N_A_12.csv')
write.csv(P_N_A_13, 'c:/Big Data Contest/P_N_A_13.csv')
write.csv(P_N_A_14, 'c:/Big Data Contest/P_N_A_14.csv')
write.csv(P_N_A_15, 'c:/Big Data Contest/P_N_A_15.csv')
write.csv(P_N_A_16, 'c:/Big Data Contest/P_N_A_16.csv')
write.csv(P_N_A_17, 'c:/Big Data Contest/P_N_A_17.csv')
write.csv(P_N_A_18, 'c:/Big Data Contest/P_N_A_18.csv')
write.csv(P_N_A_19, 'c:/Big Data Contest/P_N_A_19.csv')
write.csv(P_N_A_20, 'c:/Big Data Contest/P_N_A_20.csv')
write.csv(P_N_A_21, 'c:/Big Data Contest/P_N_A_21.csv')
write.csv(P_N_A_22, 'c:/Big Data Contest/P_N_A_22.csv')
write.csv(P_N_A_23, 'c:/Big Data Contest/P_N_A_23.csv')
write.csv(P_N_A_24, 'c:/Big Data Contest/P_N_A_24.csv')


write.csv(P_N_B_1, 'c:/Big Data Contest/P_N_B_1.csv')
write.csv(P_N_B_2, 'c:/Big Data Contest/P_N_B_2.csv')
write.csv(P_N_B_3, 'c:/Big Data Contest/P_N_B_3.csv')
write.csv(P_N_B_4, 'c:/Big Data Contest/P_N_B_4.csv')
write.csv(P_N_B_5, 'c:/Big Data Contest/P_N_B_5.csv')
write.csv(P_N_B_6, 'c:/Big Data Contest/P_N_B_6.csv')
write.csv(P_N_B_7, 'c:/Big Data Contest/P_N_B_7.csv')
write.csv(P_N_B_8, 'c:/Big Data Contest/P_N_B_8.csv')
write.csv(P_N_B_9, 'c:/Big Data Contest/P_N_B_9.csv')
write.csv(P_N_B_10, 'c:/Big Data Contest/P_N_B_10.csv')
write.csv(P_N_B_11, 'c:/Big Data Contest/P_N_B_11.csv')
write.csv(P_N_B_12, 'c:/Big Data Contest/P_N_B_12.csv')
write.csv(P_N_B_13, 'c:/Big Data Contest/P_N_B_13.csv')
write.csv(P_N_B_14, 'c:/Big Data Contest/P_N_B_14.csv')
write.csv(P_N_B_15, 'c:/Big Data Contest/P_N_B_15.csv')
write.csv(P_N_B_16, 'c:/Big Data Contest/P_N_B_16.csv')
write.csv(P_N_B_17, 'c:/Big Data Contest/P_N_B_17.csv')
write.csv(P_N_B_18, 'c:/Big Data Contest/P_N_B_18.csv')
write.csv(P_N_B_19, 'c:/Big Data Contest/P_N_B_19.csv')
write.csv(P_N_B_20, 'c:/Big Data Contest/P_N_B_20.csv')
write.csv(P_N_B_21, 'c:/Big Data Contest/P_N_B_21.csv')
write.csv(P_N_B_22, 'c:/Big Data Contest/P_N_B_22.csv')
write.csv(P_N_B_23, 'c:/Big Data Contest/P_N_B_23.csv')
write.csv(P_N_B_24, 'c:/Big Data Contest/P_N_B_24.csv')
write.csv(P_N_B_25, 'c:/Big Data Contest/P_N_B_25.csv')
write.csv(P_N_B_26, 'c:/Big Data Contest/P_N_B_26.csv')
write.csv(P_N_B_27, 'c:/Big Data Contest/P_N_B_27.csv')
write.csv(P_N_B_28, 'c:/Big Data Contest/P_N_B_28.csv')
write.csv(P_N_B_29, 'c:/Big Data Contest/P_N_B_29.csv')
write.csv(P_N_B_30, 'c:/Big Data Contest/P_N_B_30.csv')
write.csv(P_N_B_31, 'c:/Big Data Contest/P_N_B_31.csv')
write.csv(P_N_B_32, 'c:/Big Data Contest/P_N_B_32.csv')
write.csv(P_N_B_33, 'c:/Big Data Contest/P_N_B_33.csv')
write.csv(P_N_B_34, 'c:/Big Data Contest/P_N_B_34.csv')
write.csv(P_N_B_35, 'c:/Big Data Contest/P_N_B_35.csv')
write.csv(P_N_B_36, 'c:/Big Data Contest/P_N_B_36.csv')
write.csv(P_N_B_37, 'c:/Big Data Contest/P_N_B_37.csv')


write.csv(P_N_C_1, 'c:/Big Data Contest/P_N_C_1.csv')
write.csv(P_N_C_2, 'c:/Big Data Contest/P_N_C_2.csv')
write.csv(P_N_C_3, 'c:/Big Data Contest/P_N_C_3.csv')
write.csv(P_N_C_4, 'c:/Big Data Contest/P_N_C_4.csv')
write.csv(P_N_C_5, 'c:/Big Data Contest/P_N_C_5.csv')
write.csv(P_N_C_6, 'c:/Big Data Contest/P_N_C_6.csv')
write.csv(P_N_C_7, 'c:/Big Data Contest/P_N_C_7.csv')
write.csv(P_N_C_8, 'c:/Big Data Contest/P_N_C_8.csv')
write.csv(P_N_C_9, 'c:/Big Data Contest/P_N_C_9.csv')
write.csv(P_N_C_10, 'c:/Big Data Contest/P_N_C_10.csv')
write.csv(P_N_C_11, 'c:/Big Data Contest/P_N_C_11.csv')
write.csv(P_N_C_12, 'c:/Big Data Contest/P_N_C_12.csv')
write.csv(P_N_C_13, 'c:/Big Data Contest/P_N_C_13.csv')
write.csv(P_N_C_14, 'c:/Big Data Contest/P_N_C_14.csv')
write.csv(P_N_C_15, 'c:/Big Data Contest/P_N_C_15.csv')
write.csv(P_N_C_16, 'c:/Big Data Contest/P_N_C_16.csv')
write.csv(P_N_C_17, 'c:/Big Data Contest/P_N_C_17.csv')
write.csv(P_N_C_18, 'c:/Big Data Contest/P_N_C_18.csv')
write.csv(P_N_C_19, 'c:/Big Data Contest/P_N_C_19.csv')
write.csv(P_N_C_20, 'c:/Big Data Contest/P_N_C_20.csv')
write.csv(P_N_C_21, 'c:/Big Data Contest/P_N_C_21.csv')
write.csv(P_N_C_22, 'c:/Big Data Contest/P_N_C_22.csv')



write.csv(P_N_D_1, 'c:/Big Data Contest/P_N_D_1.csv')
write.csv(P_N_D_2, 'c:/Big Data Contest/P_N_D_2.csv')
write.csv(P_N_D_3, 'c:/Big Data Contest/P_N_D_3.csv')
write.csv(P_N_D_4, 'c:/Big Data Contest/P_N_D_4.csv')
write.csv(P_N_D_5, 'c:/Big Data Contest/P_N_D_5.csv')
write.csv(P_N_D_6, 'c:/Big Data Contest/P_N_D_6.csv')
write.csv(P_N_D_7, 'c:/Big Data Contest/P_N_D_7.csv')
write.csv(P_N_D_8, 'c:/Big Data Contest/P_N_D_8.csv')
write.csv(P_N_D_9, 'c:/Big Data Contest/P_N_D_9.csv')
write.csv(P_N_D_10, 'c:/Big Data Contest/P_N_D_10.csv')
write.csv(P_N_D_11, 'c:/Big Data Contest/P_N_D_11.csv')
write.csv(P_N_D_12, 'c:/Big Data Contest/P_N_D_12.csv')
write.csv(P_N_D_13, 'c:/Big Data Contest/P_N_D_13.csv')
write.csv(P_N_D_14, 'c:/Big Data Contest/P_N_D_14.csv')
write.csv(P_N_D_15, 'c:/Big Data Contest/P_N_D_15.csv')
write.csv(P_N_D_16, 'c:/Big Data Contest/P_N_D_16.csv')
write.csv(P_N_D_17, 'c:/Big Data Contest/P_N_D_17.csv')
write.csv(P_N_D_18, 'c:/Big Data Contest/P_N_D_18.csv')
write.csv(P_N_D_19, 'c:/Big Data Contest/P_N_D_19.csv')
write.csv(P_N_D_20, 'c:/Big Data Contest/P_N_D_20.csv')
write.csv(P_N_D_21, 'c:/Big Data Contest/P_N_D_21.csv')
write.csv(P_N_D_22, 'c:/Big Data Contest/P_N_D_22.csv')
write.csv(P_N_D_23, 'c:/Big Data Contest/P_N_D_23.csv')
write.csv(P_N_D_24, 'c:/Big Data Contest/P_N_D_24.csv')
write.csv(P_N_D_25, 'c:/Big Data Contest/P_N_D_25.csv')
write.csv(P_N_D_26, 'c:/Big Data Contest/P_N_D_26.csv')
write.csv(P_N_D_27, 'c:/Big Data Contest/P_N_D_27.csv')
write.csv(P_N_D_28, 'c:/Big Data Contest/P_N_D_28.csv')
write.csv(P_N_D_29, 'c:/Big Data Contest/P_N_D_29.csv')
write.csv(P_N_D_30, 'c:/Big Data Contest/P_N_D_30.csv')
write.csv(P_N_D_31, 'c:/Big Data Contest/P_N_D_31.csv')
write.csv(P_N_D_32, 'c:/Big Data Contest/P_N_D_32.csv')
write.csv(P_N_D_33, 'c:/Big Data Contest/P_N_D_33.csv')
write.csv(P_N_D_34, 'c:/Big Data Contest/P_N_D_34.csv')
write.csv(P_N_D_35, 'c:/Big Data Contest/P_N_D_35.csv')
write.csv(P_N_D_36, 'c:/Big Data Contest/P_N_D_36.csv')
write.csv(P_N_D_37, 'c:/Big Data Contest/P_N_D_37.csv')
write.csv(P_N_D_38, 'c:/Big Data Contest/P_N_D_38.csv')
write.csv(P_N_D_39, 'c:/Big Data Contest/P_N_D_39.csv')
write.csv(P_N_D_40, 'c:/Big Data Contest/P_N_D_40.csv')
write.csv(P_N_D_41, 'c:/Big Data Contest/P_N_D_41.csv')
write.csv(P_N_D_42, 'c:/Big Data Contest/P_N_D_42.csv')
write.csv(P_N_D_43, 'c:/Big Data Contest/P_N_D_43.csv')
write.csv(P_N_D_44, 'c:/Big Data Contest/P_N_D_44.csv')
write.csv(P_N_D_45, 'c:/Big Data Contest/P_N_D_45.csv')
write.csv(P_N_D_46, 'c:/Big Data Contest/P_N_D_46.csv')
write.csv(P_N_D_47, 'c:/Big Data Contest/P_N_D_47.csv')
write.csv(P_N_D_48, 'c:/Big Data Contest/P_N_D_48.csv')
write.csv(P_N_D_50, 'c:/Big Data Contest/P_N_D_50.csv')
write.csv(P_N_D_51, 'c:/Big Data Contest/P_N_D_51.csv')
write.csv(P_N_D_52, 'c:/Big Data Contest/P_N_D_52.csv')
write.csv(P_N_D_53, 'c:/Big Data Contest/P_N_D_53.csv')
write.csv(P_N_D_54, 'c:/Big Data Contest/P_N_D_54.csv')

write.csv(P_N_F_1, 'c:/Big Data Contest/P_N_F_1.csv')
write.csv(P_N_F_2, 'c:/Big Data Contest/P_N_F_2.csv')
write.csv(P_N_F_3, 'c:/Big Data Contest/P_N_F_3.csv')
write.csv(P_N_F_4, 'c:/Big Data Contest/P_N_F_4.csv')
write.csv(P_N_F_5, 'c:/Big Data Contest/P_N_F_5.csv')
write.csv(P_N_F_6, 'c:/Big Data Contest/P_N_F_6.csv')
write.csv(P_N_F_7, 'c:/Big Data Contest/P_N_F_7.csv')
write.csv(P_N_F_8, 'c:/Big Data Contest/P_N_F_8.csv')
write.csv(P_N_F_9, 'c:/Big Data Contest/P_N_F_9.csv')